kind: Namespace
apiVersion: v1
metadata:
  name: expense
  labels:
    name: expense
    environment: dev

# apiVersion: v1
# kind: Namespace
# metadata: 
#   name: expense # This is the namespace name
#   labels:
#     name: expense
#     environment: dev 