kind: Pod
apiVersion: v1
metadata:
  name: resources
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
    # Soft limit
      requests:
        cpu: "100m"
        memory: "128Mi"
    # limits should be atleast or morethan requests. This is hard limit
      limits:
        cpu: "100m"
        memory: "128Mi"