apiVersion: v1
kind: Pod
metadata:
  name: toleration
  labels:
    env: test
spec:
  containers:
  - name: nginx
    image: nginx
    imagePullPolicy: Always # Keep this as always
  tolerations:
  - key: "project"
    value: "expense"
    operator: "Equal"
    #effect: "NoSchedule"
